language: cpp
matrix:
    include:
        - compiler: clang
          env: CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Release -GNinja -DDISPATCH_ENABLE_TEST_SUITE=1"
               DISPATCH_RUN_TESTS=1
        - compiler: gcc
          env: CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Release"
cache: apt
before_install:
    - sudo apt-get update -qq
    - mkdir -p downloads
    - wget -P downloads
            http://howlingfantods.s3.amazonaws.com/packages/cmake_3.0.1_amd64.deb
    - wget -P downloads
            http://howlingfantods.s3.amazonaws.com/packages/ninja_1.5.1_amd64.deb
install:
    - sudo apt-get install -qq
            libblocksruntime-dev
            libkqueue-dev
            libpthread-workqueue-dev
            gdebi-core
            wbritish
            python-pip
    - sudo pip install click
    - sudo gdebi -n downloads/cmake_3.0.1_amd64.deb
    - sudo gdebi -n downloads/ninja_1.5.1_amd64.deb
script:
    - mkdir build && pushd build
    - cmake .. $CMAKE_FLAGS
    - cmake --build .
    - sudo cmake --build . --target install
    - popd
    - |
        if [[ "$DISPATCH_RUN_TESTS" -eq 1 ]]; then
            ./testing/run_tests.py --permitted-failures=read2,apply,vnode build/testing
        fi

